### ISSUE TITLE
docker run 

### ISSUE THREAD

**Issue by Sunyingbin** [zilliz-bootcamp/image_search_v2#1]
docker run --name zilliz_search_images_demo_web -d --rm -p 8001:80 -e API_URL=http://192.168.10.47:5000 milvusbootcamp/pic-search-webclient:0.2.0

Unable to find image 'milvusbootcamp/pic-search-webclient:0.2.0' locally
docker: Error response from daemon: Head https://registry-1.docker.io/v2/milvusbootcamp/pic-search-webclient/manifests/0.2.0: net/http: TLS handshake timeout.
See 'docker run --help'.

**Comment by jingkl** [comment]
You can refer to the link https://www.codeprj.com/blog/9e93ef1.html
